### ISSUE TITLE
请求添加bilibili专栏、AcFun专栏和ao3(Archive of Our Own)的文章抓取功能

### ISSUE THREAD

**Issue by nc-animation** [duty-machine/duty-machine-action#14]

**Comment by Nyarin-cat** [comment]
@duty-machine 
请求修复bilibili专栏的图片显示问题，以及加入bilibili动态的备份功能。

**Comment by nc-animation** [comment]
<div type='discussions-op-text'>

<sup>Originally posted by **duty-machine** Mar 1, 2021</sup>
已添加，可以试试。</div>

为什么现在无法备份b站专栏和a站文章了呢？

**Comment by nc-animation** [comment]
<div type='discussions-op-text'>

<sup>Originally posted by **duty-machine** July 10, 2021</sup>
b站专栏已修复，a站文章看起来并没有问题。如果你指的是duty-machine仓库无法使用，那个仓库已经永久停止抓取功能，请使用此action自行搭建。</div>

b站专栏无法备份图片内容，能否修复一下？

**Comment by nc-animation** [comment]
？？？
